name: Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - charts/**

jobs:
  docker:
    runs-on: ubuntu-20.04

    env:
      CR_PAT_USER: devplayer0
      REPO: ghcr.io/netsoc/website

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: image=moby/buildkit:master

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ env.CR_PAT_USER }}
          password: ${{ secrets.CI_PAT }}

      - id: vars
        name: Generate build vars
        run: |
          SHA="${{ github.sha }}"
          echo "::set-output name=tag::"${SHA:0:8}-$(date +%s)Z""

      - name: Build
        uses: docker/build-push-action@v2
        with:
          file: docker/Dockerfile
          load: true
          tags: |
            ${{ env.REPO }}:${{ steps.vars.outputs.tag }}
            ${{ env.REPO }}:latest

      # Pushing to an existing tag doesn't seem to work with buildx :(
      - name: Push
        run: docker push --all-tags "$REPO"
